# Generated by Django 2.2.5 on 2019-10-04 23:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo do Documento')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação do documento')),
                ('texto', models.CharField(max_length=99999, verbose_name='Conteudo do Documento')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Envio_de_processo',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo_eletronico.Documento')),
                ('tempo_permanencia', models.CharField(max_length=2, verbose_name="Tempo em 'dais' que o processo passou no departamento")),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo_eletronico.Departamento')),
            ],
            bases=('app_processo_eletronico.documento',),
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo_eletronico.Pessoa')),
                ('matricula', models.CharField(max_length=15, verbose_name='Número da mátriula')),
                ('dataContratacao', models.DateField(auto_now_add=True, verbose_name='Data de Inicio de contrato')),
            ],
            bases=('app_processo_eletronico.pessoa',),
        ),
        migrations.CreateModel(
            name='Pedido_de_prazo',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo_eletronico.Documento')),
                ('just', models.CharField(max_length=999, verbose_name='Justiicativa do pedido de Prazo')),
                ('nova_data', models.DateTimeField(blank=True, null=True, verbose_name='Nova data para o documnto')),
            ],
            bases=('app_processo_eletronico.documento',),
        ),
        migrations.CreateModel(
            name='Portaria_de_instauração',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_processo_eletronico.Documento')),
            ],
            bases=('app_processo_eletronico.documento',),
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_tramite', models.DateTimeField(auto_now_add=True)),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo_eletronico.Departamento')),
                ('origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app_processo_eletronico.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('documentos', models.ManyToManyField(related_name='_processo_documentos_+', to='app_processo_eletronico.Documento')),
                ('interessados', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app_processo_eletronico.Pessoa')),
                ('investigados', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo_eletronico.Pessoa')),
                ('envios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo_eletronico.Envio_de_processo')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo_eletronico.Pedido_de_prazo')),
            ],
        ),
        migrations.AddField(
            model_name='documento',
            name='criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo_eletronico.Funcionario'),
        ),
    ]
