# Generated by Django 2.2.5 on 2019-10-04 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_processo_eletronico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='documentos',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='envios',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='pedido',
        ),
        migrations.AddField(
            model_name='documento',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo_eletronico.Processo'),
        ),
        migrations.AddField(
            model_name='processo',
            name='func',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app_processo_eletronico.Funcionario'),
        ),
    ]
