# Generated by Django 2.2.5 on 2019-10-04 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_processo_eletronico', '0002_auto_20191004_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envio_de_processo',
            name='tempo_permanencia',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='data_tramite',
        ),
        migrations.AddField(
            model_name='tramite',
            name='data_envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='data_recebido',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_processo_eletronico.Processo'),
        ),
    ]
